version: '3.9'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_NAME=Minisource Blog
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_STRAPI_URL=http://cms:1337
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - minisource

networks:
  minisource:
    external: true
