version: '3.9'

services:
  # STRAPI
  strapi:
    image: CMS_IMAGE_FULL
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - "${STRAPI_PORT}:1337"
    volumes:
      - /root/cms/package.json:/app/package.json
    working_dir: /app
    command: npm run start
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data

volumes:
  strapi-data: